const analyzerSamples = {
  human: `When I first joined the lab, I expected the work to be mostly technical. What surprised me was how much of the project depended on small conversations, messy drafts, and revisions that only made sense after a few failed attempts. The final result looked polished, but the process was full of hesitation and compromise.`,
  ai: `The rapid evolution of digital communication has created a landscape in which evaluating textual authenticity is increasingly important. By examining stylistic consistency, probabilistic regularity, and cohesion under perturbation, one can systematically estimate whether a passage is likely to have been generated by an automated language model.`,
  mixed: `The café was almost empty when I started writing, and for a while the room felt quiet enough to hear the espresso machine cooling down. Still, the argument in my paper kept turning into tidy, over-explained paragraphs, as if a machine had decided that every thought needed to sound complete and perfectly balanced.`
};

const gameCases = [
  {
    label: "human",
    text: "I kept the rejection email for three weeks before deleting it. Not because I thought I could change the result, but because the wording was so polished that it almost made me feel grateful for being turned down.",
    reason: "The phrasing is specific, emotionally awkward, and anchored in a concrete personal detail."
  },
  {
    label: "ai",
    text: "In modern academic environments, students increasingly benefit from adaptive learning systems that personalize content delivery, optimize feedback cycles, and support diverse instructional outcomes across disciplines.",
    reason: "The sentence is broad, polished, and packed with abstract nouns rather than lived detail."
  },
  {
    label: "human",
    text: "My notes from the meeting looked impressive until I read them the next morning and realized I had written 'fix model confidence vibes' three separate times with no explanation.",
    reason: "There is humor, mild inconsistency, and a distinctly human kind of shorthand."
  },
  {
    label: "ai",
    text: "The integration of multimodal forensic signals provides a robust framework for identifying synthetic content while maintaining scalability and interpretability in real-world deployment settings.",
    reason: "It sounds competent, but it is too generic and too optimized for sounding formal."
  }
];

const textInput = document.querySelector("#text-input");
const analyzeBtn = document.querySelector("#analyze-btn");
const shuffleBtn = document.querySelector("#shuffle-btn");
const sampleChips = document.querySelectorAll(".sample-chip");
const modeTabs = document.querySelectorAll(".mode-tab");
const inputModes = document.querySelectorAll(".input-mode");
const verdictTitle = document.querySelector("#verdict-title");
const scoreValue = document.querySelector("#score-value");
const scoreRing = document.querySelector("#score-ring");
const meterFill = document.querySelector("#meter-fill");
const confidenceValue = document.querySelector("#confidence-value");
const ratioValue = document.querySelector("#ratio-value");
const cueValue = document.querySelector("#cue-value");
const sentenceList = document.querySelector("#sentence-list");
const featureGrid = document.querySelector("#feature-grid");
const modelStatus = document.querySelector("#model-status");
const deviceStatus = document.querySelector("#device-status");
const demoModeStatus = document.querySelector("#demo-mode-status");

const guessText = document.querySelector("#guess-text");
const roundCounter = document.querySelector("#round-counter");
const gameScore = document.querySelector("#game-score");
const answerLabel = document.querySelector("#answer-label");
const answerReason = document.querySelector("#answer-reason");
const guessHuman = document.querySelector("#guess-human");
const guessAi = document.querySelector("#guess-ai");
const revealBtn = document.querySelector("#reveal-btn");
const nextBtn = document.querySelector("#next-btn");
const imageInput = document.querySelector("#image-input");
const audioInput = document.querySelector("#audio-input");
const videoInput = document.querySelector("#video-input");
const videoUrlInput = document.querySelector("#video-url-input");
const inspectVideoBtn = document.querySelector("#inspect-video-btn");
const imageStatus = document.querySelector("#image-status");
const audioStatus = document.querySelector("#audio-status");
const videoStatus = document.querySelector("#video-status");
const imageBox = document.querySelector("#image-box");
const audioBox = document.querySelector("#audio-box");
const videoBox = document.querySelector("#video-box");
const frameBox = document.querySelector("#frame-box");
const voiceBox = document.querySelector("#voice-box");
const subtitleBox = document.querySelector("#subtitle-box");
const heatmapCard = document.querySelector(".heatmap-card");
const featureSignalsCard = document.querySelectorAll(".feature-card")[0];
const verdictKicker = document.querySelector(".results-header .section-kicker");

let score = 0;
let attempts = 0;
let currentCase = 0;
let currentMode = "text";

const modeModelMap = {
  text: "CSPF-Net",
  image: "EfficientNet-B7 + Dual Attention / Community Forensics (ViT-based)",
  audio: "Lightweight CNN on Log-Mel Spectrograms / SpecTTTra + CNN-XGBoost",
  video: "Frame + Audio + Subtitle Fusion"
};

const modeDeviceMap = {
  text: "CUDA Text Inference",
  image: "Frame GPU Inspection",
  audio: "Audio Pipeline Ready",
  video: "Frame + Audio + OCR Stack"
};

const modeDemoStatusMap = {
  text: "Live Text Analysis",
  image: "Image Intake Preview",
  audio: "Audio Intake Preview",
  video: "Link Decomposition Demo"
};

function splitSentences(text) {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function analyzeText(text) {
  const sentences = splitSentences(text);
  const wordCount = text.trim().split(/\s+/).filter(Boolean).length;
  const longWordRatio = text
    .split(/\s+/)
    .filter((word) => word.replace(/[^a-zA-Z]/g, "").length >= 8).length / Math.max(wordCount, 1);
  const punctuationDensity = (text.match(/[,:;()-]/g) || []).length / Math.max(wordCount, 1);
  const formalCueCount = (text.match(/\b(increasingly|robust|framework|systematic|deployment|optimize|landscape|furthermore)\b/gi) || []).length;
  const personalCueCount = (text.match(/\b(I|my|me|we|our|yesterday|morning|night)\b/gi) || []).length;

  let aiScore = 0.32;
  aiScore += longWordRatio * 0.85;
  aiScore += punctuationDensity * 1.1;
  aiScore += formalCueCount * 0.08;
  aiScore -= personalCueCount * 0.06;
  aiScore = clamp(aiScore, 0.06, 0.96);

  const sentenceScores = sentences.map((sentence, index) => {
    const base = aiScore + ((sentence.match(/\b(robust|systematic|increasingly|framework|scalability)\b/gi) || []).length * 0.09);
    const personalOffset = (sentence.match(/\b(I|my|me|we)\b/gi) || []).length * 0.08;
    return clamp(base - personalOffset + (index % 2 === 0 ? 0.02 : -0.01), 0.05, 0.98);
  });

  const suspiciousCount = sentenceScores.filter((score) => score >= 0.58).length;
  const confidence = clamp(0.56 + Math.abs(aiScore - 0.5) * 0.88, 0.51, 0.97);
  const verdict = aiScore >= 0.55 ? "Likely AI" : aiScore <= 0.4 ? "Likely Human" : "Borderline / Mixed";

  let cue = "Balanced stylistic signals";
  if (formalCueCount >= 2) cue = "Overly polished abstraction";
  if (personalCueCount >= 2) cue = "Concrete personal detail";
  if (suspiciousCount > sentences.length / 2) cue = "Sentence-level consistency spike";

  return {
    verdict,
    aiScore,
    confidence,
    suspiciousCount,
    sentenceScores,
    sentences,
    cue,
    features: [
      {
        name: "Style entropy",
        value: `${Math.round((1 - longWordRatio) * 100)}%`,
        detail: longWordRatio > 0.24 ? "Dense academic diction" : "More natural lexical spread"
      },
      {
        name: "Probabilistic regularity",
        value: `${Math.round(aiScore * 100)}%`,
        detail: aiScore > 0.55 ? "Higher LM-likeness" : "Less templated flow"
      },
      {
        name: "Cohesion stress test",
        value: `${Math.round((0.4 + punctuationDensity * 4) * 100)}%`,
        detail: punctuationDensity > 0.09 ? "Rigid sentence packing" : "Looser human rhythm"
      }
    ]
  };
}

function renderAnalysis(result) {
  const scorePercent = Math.round(result.aiScore * 100);
  verdictTitle.textContent = result.verdict;
  scoreValue.textContent = `${scorePercent}%`;
  confidenceValue.textContent = `${Math.round(result.confidence * 100)}%`;
  ratioValue.textContent = `${result.suspiciousCount} / ${result.sentences.length || 1}`;
  cueValue.textContent = result.cue;
  meterFill.style.width = `${scorePercent}%`;
  scoreRing.style.background = `conic-gradient(var(--bad) 0deg, var(--bad) ${scorePercent * 3.6}deg, rgba(255, 255, 255, 0.08) ${scorePercent * 3.6}deg)`;

  sentenceList.innerHTML = "";
  result.sentences.forEach((sentence, index) => {
    const score = result.sentenceScores[index];
    const item = document.createElement("article");
    item.className = "sentence-item";
    item.style.borderLeftColor = `hsl(${120 - score * 120} 90% 65%)`;
    item.style.background = `linear-gradient(90deg, rgba(255, 95, 109, ${score * 0.24}), rgba(255, 255, 255, 0.03))`;
    item.innerHTML = `
      <div class="sentence-meta">
        <span>Sentence ${index + 1}</span>
        <span>${Math.round(score * 100)}% AI-likely</span>
      </div>
      <div>${sentence}</div>
    `;
    sentenceList.appendChild(item);
  });

  featureGrid.innerHTML = "";
  result.features.forEach((feature) => {
    const box = document.createElement("article");
    box.className = "feature-box";
    box.innerHTML = `
      <span class="stat-label">${feature.name}</span>
      <strong>${feature.value}</strong>
      <p>${feature.detail}</p>
    `;
    featureGrid.appendChild(box);
  });
}

function setSample(sampleKey) {
  textInput.value = analyzerSamples[sampleKey];
  renderAnalysis(analyzeText(textInput.value));
}

function renderGameCase() {
  const item = gameCases[currentCase];
  guessText.textContent = item.text;
  roundCounter.textContent = `Case ${currentCase + 1} / ${gameCases.length}`;
  answerLabel.textContent = "Hidden";
  answerReason.textContent = "Ask the room to vote first, then reveal the explanation.";
}

function setMode(mode) {
  currentMode = mode;
  modelStatus.textContent = modeModelMap[mode] || "CSPF-Net";
  deviceStatus.textContent = modeDeviceMap[mode] || "Runtime Ready";
  demoModeStatus.textContent = modeDemoStatusMap[mode] || "Frontend Prototype";
  modeTabs.forEach((tab) => {
    tab.classList.toggle("active", tab.dataset.mode === mode);
  });
  inputModes.forEach((panel) => {
    panel.classList.toggle("active", panel.dataset.panel === mode);
  });

  const isText = mode === "text";
  heatmapCard.style.display = isText ? "" : "none";

  const featureHeadings = {
    text: "Feature Signals",
    image: "Detection Breakdown",
    audio: "Audio Analysis",
    video: "Multimodal Breakdown",
  };
  featureSignalsCard.querySelector("h4").textContent = featureHeadings[mode] || "Feature Signals";
  featureSignalsCard.querySelector("span").textContent = isText ? "Designed for classroom explanation" : "Per-modality confidence scores";

  const kickers = {
    text: "Document Verdict",
    image: "Image Verdict",
    audio: "Audio Verdict",
    video: "Video Verdict",
  };
  verdictKicker.textContent = kickers[mode] || "Verdict";

  if (!isText) featureGrid.innerHTML = "";
}

function updateModalityBox(box, label, detail) {
  box.classList.add("active");
  box.innerHTML = `
    <span class="stat-label">${label}</span>
    <strong>Loaded</strong>
    <p>${detail}</p>
  `;
}

function updateDecompositionBox(box, label, title, detail) {
  box.classList.add("active");
  box.innerHTML = `
    <span class="stat-label">${label}</span>
    <strong>${title}</strong>
    <p>${detail}</p>
  `;
}

function inspectVideoSource(sourceLabel) {
  videoStatus.textContent = `${sourceLabel} accepted. The demo will decompose the video into image frames, audio, and subtitles for separate forensic checks.`;
  updateModalityBox(videoBox, "Video", `${sourceLabel} mapped to a multimodal decomposition workflow.`);
  updateDecompositionBox(frameBox, "Frame Track", "Queued", "Sample keyframes would be extracted and sent to the image branch for visual artifact checks.");
  updateDecompositionBox(voiceBox, "Audio Track", "Queued", "The soundtrack would be separated for speech analysis and synthetic-voice cues.");
  updateDecompositionBox(subtitleBox, "Subtitle Track", "Queued", "OCR or ASR output would be routed into the text detector for language-based forensics.");
}

// ── Backend result renderers ──────────────────────────────────────────────────

function renderImageResult(data) {
  const fakePct = Math.round(data.fake_prob * 100);
  const realPct = Math.round(data.real_prob * 100);
  const confPct = Math.round(data.confidence * 100);
  const isFake = data.label === "FAKE";
  const ringPct = isFake ? fakePct : confPct;
  const ringColor = isFake ? "var(--bad)" : "var(--good)";

  verdictTitle.textContent = isFake ? "AI-Generated Image" : "Authentic Image";
  scoreValue.textContent = `${ringPct}%`;
  confidenceValue.textContent = `${confPct}%`;
  ratioValue.textContent = "—";
  cueValue.textContent = isFake ? "Visual artifacts detected" : "No synthetic artifacts found";
  meterFill.style.width = `${fakePct}%`;
  scoreRing.style.background = `conic-gradient(${ringColor} 0deg, ${ringColor} ${ringPct * 3.6}deg, rgba(255,255,255,0.08) ${ringPct * 3.6}deg)`;
  sentenceList.innerHTML = "";

  featureGrid.innerHTML = "";
  [
    { name: "AI probability",   value: `${fakePct}%`,  detail: isFake ? "Above detection threshold (50%)" : "Below detection threshold (50%)" },
    { name: "Real probability", value: `${realPct}%`,  detail: isFake ? "Low authenticity confidence" : "High authenticity confidence" },
    { name: "Model",            value: "EfficientNet-B7", detail: "Fine-tuned on deepfake face dataset" },
  ].forEach(({ name, value, detail }) => {
    const box = document.createElement("article");
    box.className = "feature-box";
    box.innerHTML = `<span class="stat-label">${name}</span><strong>${value}</strong><p>${detail}</p>`;
    featureGrid.appendChild(box);
  });

  imageBox.classList.add("active");
  imageBox.innerHTML = `
    <span class="stat-label">Image</span>
    <strong style="color:${ringColor}">${data.label}</strong>
    <p>Fake ${fakePct}% · Real ${realPct}% · Conf ${confPct}%</p>
  `;
}

function renderAudioResult(data) {
  const pct = Math.round(data.prob_fake * 100);
  const isFake = data.prediction === "fake";
  const ringColor = isFake ? "var(--bad)" : "var(--good)";

  verdictTitle.textContent = isFake ? "Synthetic Audio" : "Authentic Audio";
  scoreValue.textContent = `${pct}%`;
  confidenceValue.textContent = data.risk_level;
  ratioValue.textContent = "—";
  cueValue.textContent = `Risk level: ${data.risk_level}`;
  meterFill.style.width = `${pct}%`;
  scoreRing.style.background = `conic-gradient(${ringColor} 0deg, ${ringColor} ${pct * 3.6}deg, rgba(255,255,255,0.08) ${pct * 3.6}deg)`;
  sentenceList.innerHTML = "";

  featureGrid.innerHTML = "";
  [
    { name: "Fake probability", value: `${pct}%`,           detail: isFake ? "Synthetic voice detected" : "No synthetic voice detected" },
    { name: "Risk level",       value: data.risk_level,     detail: pct < 30 ? "Low likelihood of AI generation" : pct < 70 ? "Moderate — manual review advised" : "High likelihood of AI generation" },
    { name: "Model",            value: "Random Forest",     detail: "MFCC + spectral feature extraction" },
  ].forEach(({ name, value, detail }) => {
    const box = document.createElement("article");
    box.className = "feature-box";
    box.innerHTML = `<span class="stat-label">${name}</span><strong>${value}</strong><p>${detail}</p>`;
    featureGrid.appendChild(box);
  });

  audioBox.classList.add("active");
  audioBox.innerHTML = `
    <span class="stat-label">Audio</span>
    <strong style="color:${ringColor}">${data.prediction.toUpperCase()}</strong>
    <p>Fake prob ${pct}% · Risk: ${data.risk_level}</p>
  `;
}

function mapBackendTextResult(data) {
  const aiScore = data.ai_probability;
  const sentences = data.sentences || [];
  const sentenceScores = data.sentence_probabilities || [];
  const suspiciousCount = sentenceScores.filter((s) => s >= 0.58).length;
  const confidence = Math.min(0.97, 0.56 + Math.abs(aiScore - 0.5) * 0.88);
  const verdict = aiScore >= 0.55 ? "Likely AI" : aiScore <= 0.4 ? "Likely Human" : "Borderline / Mixed";
  let cue = "CSPF-Net probabilistic analysis";
  if (aiScore > 0.7) cue = "High AI probability across document";
  else if (aiScore < 0.3) cue = "Strong human writing patterns";
  return {
    verdict, aiScore, confidence, suspiciousCount, sentenceScores, sentences, cue,
    features: [
      { name: "Document AI probability", value: `${Math.round(aiScore * 100)}%`, detail: aiScore > 0.55 ? "Document skews AI-generated" : "Document skews human-written" },
      { name: "AI sentence ratio", value: `${Math.round(data.ai_sentence_ratio * 100)}%`, detail: `${suspiciousCount} of ${sentences.length} sentences flagged AI-likely` },
      { name: "Model", value: "CSPF-Net", detail: "Context-aware sentence probability fusion" }
    ]
  };
}

function revealCase(showAnswerOnly = false) {
  const item = gameCases[currentCase];
  answerLabel.textContent = item.label === "ai" ? "AI-generated" : "Human-written";
  answerReason.textContent = item.reason;
  if (!showAnswerOnly) {
    gameScore.textContent = `${score} / ${attempts}`;
  }
}

guessHuman.addEventListener("click", () => {
  attempts += 1;
  if (gameCases[currentCase].label === "human") score += 1;
  revealCase();
});

guessAi.addEventListener("click", () => {
  attempts += 1;
  if (gameCases[currentCase].label === "ai") score += 1;
  revealCase();
});

revealBtn.addEventListener("click", () => revealCase(true));
nextBtn.addEventListener("click", () => {
  currentCase = (currentCase + 1) % gameCases.length;
  renderGameCase();
});

analyzeBtn.addEventListener("click", async () => {
  const text = textInput.value.trim();
  if (!text) return;
  verdictTitle.textContent = "Analyzing…";
  try {
    const res = await fetch("/api/detect/text", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });
    renderAnalysis(res.ok ? mapBackendTextResult(await res.json()) : analyzeText(text));
  } catch {
    renderAnalysis(analyzeText(text));
  }
});

shuffleBtn.addEventListener("click", () => {
  const keys = Object.keys(analyzerSamples);
  const randomKey = keys[Math.floor(Math.random() * keys.length)];
  setSample(randomKey);
});

sampleChips.forEach((chip) => {
  chip.addEventListener("click", () => setSample(chip.dataset.sample));
});

modeTabs.forEach((tab) => {
  tab.addEventListener("click", () => setMode(tab.dataset.mode));
});

imageInput.addEventListener("change", async () => {
  const file = imageInput.files?.[0];
  if (!file) return;

  // Show inline preview
  const uploadCard = document.querySelector('[data-panel="image"] .upload-card');
  const old = uploadCard.querySelector("img");
  if (old) old.remove();
  const preview = document.createElement("img");
  preview.src = URL.createObjectURL(file);
  preview.style.cssText = "width:100%;border-radius:12px;margin-bottom:12px;max-height:220px;object-fit:cover;";
  uploadCard.prepend(preview);

  imageStatus.textContent = `Analyzing ${file.name}…`;
  updateModalityBox(imageBox, "Image", "Running EfficientNet-B7…");
  const fd = new FormData();
  fd.append("file", file);
  try {
    const res = await fetch("/api/detect/image", { method: "POST", body: fd });
    if (res.ok) {
      renderImageResult(await res.json());
      imageStatus.textContent = `${file.name} — analysis complete.`;
    } else {
      const err = await res.json();
      imageStatus.textContent = `Error: ${err.detail}`;
      updateModalityBox(imageBox, "Image", `Error: ${err.detail}`);
    }
  } catch {
    imageStatus.textContent = `${file.name} loaded (backend not reachable — start the server first).`;
    updateModalityBox(imageBox, "Image", `${file.name} accepted. Start backend to analyze.`);
  }
});

audioInput.addEventListener("change", async () => {
  const file = audioInput.files?.[0];
  if (!file) return;
  audioStatus.textContent = `Analyzing ${file.name}…`;
  updateModalityBox(audioBox, "Audio", "Running speech detector…");
  const fd = new FormData();
  fd.append("file", file);
  try {
    const res = await fetch("/api/detect/audio", { method: "POST", body: fd });
    if (res.ok) {
      renderAudioResult(await res.json());
      audioStatus.textContent = `${file.name} — analysis complete.`;
    } else {
      const err = await res.json();
      audioStatus.textContent = `Model not loaded: ${err.detail.split(".")[0]}.`;
      updateModalityBox(audioBox, "Audio", "Model not loaded — run train_random_forest.py first.");
    }
  } catch {
    audioStatus.textContent = `${file.name} loaded (backend not reachable — start the server first).`;
    updateModalityBox(audioBox, "Audio", `${file.name} accepted. Start backend to analyze.`);
  }
});

videoInput.addEventListener("change", async () => {
  const file = videoInput.files?.[0];
  if (!file) return;
  videoStatus.textContent = `Uploading ${file.name}… this may take a moment.`;
  updateModalityBox(videoBox, "Video", "Uploading…");
  updateDecompositionBox(frameBox, "Frame Track", "Analyzing…", "Extracting keyframes…");
  updateDecompositionBox(voiceBox, "Audio Track", "Analyzing…", "Separating audio…");
  updateDecompositionBox(subtitleBox, "Subtitle Track", "Analyzing…", "Running ASR…");
  const fd = new FormData();
  fd.append("file", file);
  try {
    const res = await fetch("/api/detect/video", { method: "POST", body: fd });
    if (!res.ok) {
      videoStatus.textContent = `Server error analyzing ${file.name}.`;
      return;
    }
    const data = await res.json();
    const pct = data.fused_score != null ? Math.round(data.fused_score * 100) : null;
    videoStatus.textContent = `${file.name} — ${data.final_label}${pct != null ? ` (${pct}% AI score)` : ""}.`;
    videoBox.classList.add("active");
    videoBox.innerHTML = `
      <span class="stat-label">Video</span>
      <strong>${data.final_label}</strong>
      <p>${pct != null ? `Fused AI score: ${pct}%` : "No score available"}</p>
    `;
    const img = data.modalities?.image;
    if (img?.error) {
      updateDecompositionBox(frameBox, "Frame Track", "Error", img.error.slice(0, 80));
    } else if (img) {
      updateDecompositionBox(frameBox, "Frame Track", `${img.label} (${Math.round(img.fake_prob * 100)}%)`, `${img.frames_analyzed} frames analyzed · fake prob ${Math.round(img.fake_prob * 100)}%`);
    }
    const aud = data.modalities?.audio;
    if (aud?.error) {
      updateDecompositionBox(voiceBox, "Audio Track", "Model Not Loaded", aud.error.split(".")[0]);
    } else if (aud) {
      updateDecompositionBox(voiceBox, "Audio Track", `${aud.prediction.toUpperCase()} (${Math.round(aud.prob_fake * 100)}%)`, `Risk: ${aud.risk_level}`);
    }
    const txt = data.modalities?.text;
    if (txt?.error) {
      updateDecompositionBox(subtitleBox, "Subtitle Track", "Not Available", txt.error.split(".")[0]);
    } else if (txt) {
      const snippet = txt.transcript ? `"${txt.transcript.slice(0, 60)}…"` : "";
      updateDecompositionBox(subtitleBox, "Subtitle Track", `${txt.label} (${Math.round(txt.ai_probability * 100)}%)`, snippet);
    }
  } catch {
    videoStatus.textContent = `${file.name} loaded (backend not reachable — start the server first).`;
    inspectVideoSource(file.name);
  }
});

function renderVideoResult(data) {
  const pct = data.fused_score != null ? Math.round(data.fused_score * 100) : null;
  const isFake = data.final_label?.includes("FAKE") || data.final_label?.includes("AI");
  const ringColor = isFake ? "var(--bad)" : "var(--good)";

  verdictTitle.textContent = data.final_label || "Unknown";
  scoreValue.textContent = pct != null ? `${pct}%` : "—";
  confidenceValue.textContent = pct != null ? `${pct}%` : "—";
  ratioValue.textContent = "3 tracks";
  cueValue.textContent = "Frame + Audio + Transcript";
  if (pct != null) {
    meterFill.style.width = `${pct}%`;
    scoreRing.style.background = `conic-gradient(${ringColor} 0deg, ${ringColor} ${pct * 3.6}deg, rgba(255,255,255,0.08) ${pct * 3.6}deg)`;
  }
  sentenceList.innerHTML = "";

  featureGrid.innerHTML = "";
  const img = data.modalities?.image;
  const aud = data.modalities?.audio;
  const txt = data.modalities?.text;
  [
    {
      name: "Frame track",
      value: img?.error ? "Error" : img ? `${Math.round(img.fake_prob * 100)}% fake` : "—",
      detail: img?.error ? img.error.slice(0, 60) : img ? `${img.frames_analyzed} frames · EfficientNet-B7` : "Not analyzed"
    },
    {
      name: "Audio track",
      value: aud?.error ? "Error" : aud ? `${Math.round(aud.prob_fake * 100)}% fake` : "—",
      detail: aud?.error ? aud.error.split(".")[0] : aud ? `Risk: ${aud.risk_level} · Random Forest` : "Not analyzed"
    },
    {
      name: "Transcript track",
      value: txt?.error ? "Error" : txt ? `${Math.round(txt.ai_probability * 100)}% AI` : "—",
      detail: txt?.error ? txt.error.split(".")[0] : txt?.transcript ? `"${txt.transcript.slice(0, 50)}…"` : "No speech"
    },
  ].forEach(({ name, value, detail }) => {
    const box = document.createElement("article");
    box.className = "feature-box";
    box.innerHTML = `<span class="stat-label">${name}</span><strong>${value}</strong><p>${detail}</p>`;
    featureGrid.appendChild(box);
  });

  videoBox.classList.add("active");
  videoBox.innerHTML = `
    <span class="stat-label">Video</span>
    <strong style="color:${ringColor}">${data.final_label}</strong>
    <p>${pct != null ? `Fused AI score: ${pct}%` : "No score available"}</p>
  `;

  if (img?.error) {
    updateDecompositionBox(frameBox, "Frame Track", "Error", img.error.slice(0, 80));
  } else if (img) {
    updateDecompositionBox(frameBox, "Frame Track", `${img.label} (${Math.round(img.fake_prob * 100)}%)`, `${img.frames_analyzed} frames · fake prob ${Math.round(img.fake_prob * 100)}%`);
  }
  if (aud?.error) {
    updateDecompositionBox(voiceBox, "Audio Track", "Model Not Loaded", aud.error.split(".")[0]);
  } else if (aud) {
    updateDecompositionBox(voiceBox, "Audio Track", `${aud.prediction.toUpperCase()} (${Math.round(aud.prob_fake * 100)}%)`, `Risk: ${aud.risk_level}`);
  }
  if (txt?.error) {
    updateDecompositionBox(subtitleBox, "Subtitle Track", "Not Available", txt.error.split(".")[0]);
  } else if (txt) {
    const snippet = txt.transcript ? `"${txt.transcript.slice(0, 60)}…"` : "No speech detected";
    updateDecompositionBox(subtitleBox, "Subtitle Track", `${txt.label} (${Math.round(txt.ai_probability * 100)}%)`, snippet);
  }
}

let _activeVideoStream = null;

function setVideoAnalyzing(active) {
  inspectVideoBtn.disabled = active;
  inspectVideoBtn.textContent = active ? "Analyzing…" : "Inspect Video Link";
}

function applyVideoStepToUI(step, msg) {
  const frameSteps = new Set(["download", "downloaded", "frames", "frames_analyze", "frames_done", "frames_error"]);
  const audioSteps = new Set(["audio", "audio_analyze", "audio_done", "audio_error"]);
  const textSteps  = new Set(["asr", "text_analyze", "text_done", "text_error"]);

  videoStatus.textContent = msg;

  if (frameSteps.has(step)) {
    const status = step.endsWith("_done") ? "Done ✓" : step.endsWith("_error") ? "Error" : "Running…";
    updateDecompositionBox(frameBox, "Frame Track", status, msg);
  }
  if (audioSteps.has(step)) {
    const status = step.endsWith("_done") ? "Done ✓" : step.endsWith("_error") ? "Error" : "Running…";
    updateDecompositionBox(voiceBox, "Audio Track", status, msg);
  }
  if (textSteps.has(step)) {
    const status = step.endsWith("_done") ? "Done ✓" : step.endsWith("_error") ? "Error" : "Running…";
    updateDecompositionBox(subtitleBox, "Subtitle Track", status, msg);
  }
}

inspectVideoBtn.addEventListener("click", () => {
  const url = videoUrlInput.value.trim();
  if (!url) {
    videoStatus.textContent = "Paste a video URL first (YouTube, YouTube Shorts, etc.).";
    return;
  }

  if (_activeVideoStream) {
    _activeVideoStream.close();
    _activeVideoStream = null;
  }

  setVideoAnalyzing(true);
  videoStatus.textContent = "连接后端，准备分析…";
  updateDecompositionBox(frameBox, "Frame Track", "Waiting…", "等待分析开始");
  updateDecompositionBox(voiceBox, "Audio Track", "Waiting…", "等待分析开始");
  updateDecompositionBox(subtitleBox, "Subtitle Track", "Waiting…", "等待分析开始");

  const es = new EventSource(`/api/detect/video-url/stream?url=${encodeURIComponent(url)}`);
  _activeVideoStream = es;

  es.onmessage = (event) => {
    let data;
    try { data = JSON.parse(event.data); } catch { return; }

    applyVideoStepToUI(data.step, data.msg);

    if (data.step === "complete") {
      es.close();
      _activeVideoStream = null;
      setVideoAnalyzing(false);
      if (data.result) {
        renderVideoResult(data.result);
        const pct = data.result.fused_score != null ? Math.round(data.result.fused_score * 100) : null;
        videoStatus.textContent = `分析完成 — ${data.result.final_label}${pct != null ? `（综合 AI 得分 ${pct}%）` : ""}`;
      }
    }

    if (data.step === "error") {
      es.close();
      _activeVideoStream = null;
      setVideoAnalyzing(false);
      videoStatus.textContent = `错误: ${data.msg}`;
    }
  };

  es.onerror = () => {
    es.close();
    _activeVideoStream = null;
    setVideoAnalyzing(false);
    if (videoStatus.textContent.startsWith("连接")) {
      videoStatus.textContent = "后端不可达 — 请先启动服务器。";
    }
  };
});

setSample("human");
renderGameCase();
setMode(currentMode);
